# properteis --> yaml

server:

  port: 8080 #
    
spring:
  mvc:
    
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        show_sql: false 
    
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/combuy?characterEncoding=UTF-8&serverTimezone=UTC
    username: latte
    password: 11111111

  